FROM mongo:6.0.4-jammy

ENV TZ=Asia/Seoul
ENV PATH /usr/bin:/bin:/usr/local/bin:$PATH
ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y vim

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN dpkg-reconfigure --frontend noninteractive tzdata
